### ISSUE TITLE
Form

### ISSUE THREAD

**Issue by Axltop** [ChallengesInternshipProject/DareOrNot#1]
Can new dare and user form to be in form tag with attribute enctype="multipart/form-data" and to use ng-sumbit ?

**Comment by m0sh1x2** [comment]
Yeah possible :

```
<form ng-submit="submitDare()" enctype="multipart/form-data">
<input type="submit" class="button button-block button-balanced" >Create</input>
</form>
```

But the post request comes from the $scope.submitDare() function.
Maybe this can help ? https://uncorkedstudios.com/blog/multipartformdata-file-upload-with-angularjs
